language: emacs-lisp
sudo: required

env:
 - EVM_EMACS=emacs-25.1-travis
 - EVM_EMACS=emacs-26.1-travis
 - EVM_EMACS=emacs-git-snapshot-travis

matrix:
  fast_finish: true
  allow_failures:
    env:
      - EVM_EMACS=emacs-git-snapshot-travis

before_script:
  - mv -f ../.emacs.d ~/.emacs.d
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  # - mkdir -p lib && curl https://raw.githubusercontent.com/nschum/elisp-lint/stable/elisp-lint.el > lib/elisp-lint.el

script:
  - emacs --version
  - cd ~/.emacs.d
  - emacs --batch -l init.el -f batch-byte-compile init.el
  # - emacs --version && emacs -Q --batch --eval '(byte-recompile-directory (expand-file-name "lisp" user-emacs-directory) 0 0)'

  # - emacs -Q --batch --eval '(add-to-list (quote load-path) (expand-file-name "lisp" user-emacs-directory))' --eval '(package-initialize)' -l init.el &
  # - sleep 180
  # - emacs -Q --batch -l lib/elisp-lint.el -f elisp-lint-files-batch --no-indent --no-indent-character --no-fill-column init.el
  # - cd lisp
  # - emacs -Q --batch --eval '(add-to-list (quote load-path) (expand-file-name "lisp" user-emacs-directory))' --eval '(package-initialize)' -l ../lib/elisp-lint.el -f elisp-lint-files-batch --no-indent --no-indent-character --no-fill-column *.el
